layout_spectrum: 0.4070798
typography_spectrum: 0.1982989
color:
  lightness: 0
  brandStrength: 0.3811175
  saturation: 0
  rhythmicContrast: 0
  brandColors:
    - '#FFFFFF'
    - '#C9C8C4'
    - '#9A9A9A'
    - '#858585'
    - '#595750'
name: London Centric Interiors
